#!/usr/bin/env python3
"""Render docs/pieces.md from packages/data/machines.json. Regenerate after editing the roster."""
import json, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
data = json.loads((ROOT / "packages/data/machines.json").read_text())
pieces = data["pieces"]

SKILLS = {
    # --- attack-from-terrain bonuses: one per terrain tier from Grassland up ---
    "Gallop":     "Attacking **from Grassland**: +1 Combat Power.",
    "Stalk":      "Attacking **from Forest**: +1 Combat Power.",
    "Climb":      "Attacking **from Hill**: +1 Combat Power.",
    "High Ground":"Attacking **from Mountain**: +1 Combat Power.",
    # --- terrain conversion on attack: always the TARGET's tile ---
    "Burn":       "Attacking a machine on **Forest** turns that tile to Grassland.",
    "Freeze":     "Attacking a machine on **Marsh** turns that tile to Grassland.",
    "Growth":     "Attacking a machine on **Grassland** turns that tile to Forest.",
    "Alter Terrain":
                  "After inflicting damage: the terrain under **your** machine lowers a step, "
                  "the terrain under the **target** rises a step. No terrain gate.",
    # --- start-of-turn auras ---
    "Empower":    "Start of turn: friendly machines within Attack Range gain +1 Attack Power. Stacks.",
    "Spray":      "Start of turn: all pieces within Attack Range lose 1 Health.",
    "Whiplash":   "Start of turn: all pieces within Attack Range rotate 180°.",
    "Blind":      "Enemy machines within Attack Range lose 1 Attack Power for the rest of the turn. Stacks.",
    # --- defensive / reactive ---
    "Shield":     "+1 Combat Power when **defending**.",
    "Retaliate":  "On being attacked: rotates to face its attacker and deals 1 damage, if the attacker is in range.",
    # --- area attack ---
    "Sweep":      "Hits the target **and any machines perpendicular to it**. The exact area is per-piece: "
                  "Ravager 1×3 two tiles ahead; Thunderjaw and Tremortusk 1×3 directly in front; "
                  "Stormbird 3×3 in front.",
}

def sides(xs): return ",".join(xs) if xs else "–"

out = []
out.append("# Machine Strike — Piece Stats\n")
out.append("> Generated by `tools/gen_pieces_table.py` from [`packages/data/machines.json`]"
           "(../packages/data/machines.json).\n> Edit the JSON, not this file.\n")
out.append(f"Source: [Horizon Wiki — Machine Strike](https://horizon.fandom.com/wiki/Machine_Strike), "
           f"retrieved 2026-08-28. **{len(pieces)} pieces.**\n")
out.append("**Points** is one number serving two roles: the setup cost to field the piece, and the victory "
           "points your opponent gains when it dies. A legal team totals **exactly 10** points, "
           "max 4 identical pieces.\n")
out.append("**Armor** sides reduce incoming damage (and can hurt the attacker); **Weak** sides increase it. "
           "Sides are in the piece's own frame — F/B/L/R — and any side in neither column is neutral.\n")

TYPE_ORDER = ["Melee", "Gunner", "Ram", "Dash", "Swoop", "Pull"]
hdr = ["Machine","Type","HP","Atk","Rng","Mov","Armor","Weak","Pts","Skill","Rarity"]
out.append("| " + " | ".join(hdr) + " |")
out.append("|" + "---|"*len(hdr))
for p in sorted(pieces, key=lambda p: (TYPE_ORDER.index(p["type"]), p["points"], p["name"])):
    out.append("| " + " | ".join([
        p["name"], p["type"], str(p["health"]), str(p["attack"]), str(p["range"]),
        str(p["movement"]), sides(p["armor"]), sides(p["weak"]), str(p["points"]),
        p["skill"] or "–", p["rarity"],
    ]) + " |")

from collections import Counter, defaultdict
out.append("\n## Skills\n")
out.append("All fifteen skills are specified. They collapse into a handful of mechanisms rather than fifteen "
           "special cases: four *attack-from-terrain* bonuses (one per terrain tier from Grassland up), three "
           "*terrain conversions* on the target's tile, four *start-of-turn auras*, two defensive/reactive "
           "effects, plus `Sweep` and `Alter Terrain`.\n")
out.append("| Skill | Pieces | Effect |")
out.append("|---|---|---|")
counts = Counter(p["skill"] for p in pieces if p["skill"])
for skill, n in sorted(counts.items(), key=lambda kv: (-kv[1], kv[0])):
    users = ", ".join(sorted(p["name"] for p in pieces if p["skill"] == skill))
    effect = SKILLS.get(skill, "**UNDOCUMENTED**")
    out.append(f"| {skill} | {users} | {effect} |")

out.append("\n## Armor / weak patterns\n")
out.append("Ten distinct facing layouts across the roster. Each is one placeholder sprite "
           "(`assets/pieces/placeholder/`) and one row in the facing-damage golden tests.\n")
out.append("| Armor | Weak | Neutral | Count | Example |")
out.append("|---|---|---|---|---|")
pats = defaultdict(list)
for p in pieces: pats[(tuple(p["armor"]), tuple(p["weak"]))].append(p["name"])
for (a, w), names in sorted(pats.items(), key=lambda kv: -len(kv[1])):
    neutral = [s for s in "FBLR" if s not in a and s not in w]
    out.append(f"| {sides(list(a))} | {sides(list(w))} | {sides(neutral)} | {len(names)} | {sorted(names)[0]} |")

(ROOT / "docs/pieces.md").write_text("\n".join(out) + "\n")
print("wrote docs/pieces.md")
